### ISSUE TITLE
About the LP objective

### ISSUE THREAD

**Issue by dannalily** [tomsherborne/zx-parse#1]
Hi Tom, 

Thanks for your amazing work. I am very interested in it. In the paper, you mentioned that "we reverse this gradient in the backward pass before the LP network". Does this mean you use total_loss ( LF + NL - LP ) to update the encoder, and use LP loss to update LP decoder?

BTW, looking forward to your code :)

**Comment by tomsherborne** [comment]
Hello!

We do not optimise against this loss in the final function as this would not train the domain predictor correctly. See here https://github.com/tomsherborne/zx-parse/blob/662757d5b97a51cfa90a0620336e6ee5db9cab5e/zxp/models/seq2seq_multihead_lambda.py#L167

For applying the reversal layer function https://github.com/tomsherborne/zx-parse/blob/main/zxp/modules/gradient_reversal_layer.py

The gradient is un-reversed when passing through the domain prediction and then reversed when going further backwards (i.e. through the encoder).
